default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      force: true,
      metadata_path: "./fastlane/metadata",
      screenshots_path: "./fastlane/screenshots",
      overwrite_screenshots: true,
      submit_for_review: false,
      automatic_release: false,
      precheck_include_in_app_purchases: false,
    )
  end

  desc "Upload screenshots only"
  lane :screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: false,
      force: true,
      screenshots_path: "./fastlane/screenshots",
      overwrite_screenshots: true,
    )
  end

  desc "Submit for review"
  lane :submit do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: false,
      submission_information: {
        add_id_info_uses_idfa: false,
      },
    )
  end
end
